# import userbot by apis
# Credits by @zeafeya
# Group Support t.me/zeafeya & Channel Support t.me/Storezeastore
# KALO COPAS JANGAN HAPUS INI KONTOLLLLL

from time import sleep


from userbot import CMD_HELP, CMD_HANDLER as cmd
from userbot.utils import man_cmd
from userbot.utils import edit_or_reply, man_cmd


@man_cmd(pattern="wibu2(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(0.07)
    await typew.edit("**Sial Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Sekuat Apapun Aku😭**")
    sleep(0.07)
    await typew.edit("**Jika Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Aku Harus Lari🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Cukkk Ada Wibuuu🏃🏻**")
    sleep(0.07)
    await typew.edit("**Argghh Bangkeee!🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Sekencang-Kencangnya🤸🏻**")
    sleep(0.07)
    await typew.edit("**Karena Kita Sedang🤾🏻**")
    sleep(0.07)
    await typew.edit("**Menghadapi Ras Terkuat🤸🏻**")
    sleep(0.07)
    await typew.edit("**Yang Ada Di Dunia🏃🏻**")
    sleep(0.07)
    await typew.edit("**Wibuuuu🪂**")
    sleep(0.07)
    await typew.edit("**Arghhhhhhh🧗🏻**")
    sleep(0.07)
    await typew.edit("**Istrinya Kartun🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu😨**")
    sleep(0.07)
    await typew.edit("**Maaf Wibu🤼‍♂️**")
    sleep(0.07)
    await typew.edit("**Aku Tidak Akan🤾🏻**")
    sleep(0.07)
    await typew.edit("**Mengulanginya Lagi🏃🏻**")
    sleep(0.07)
    await typew.edit("**Tapi Bo'ong🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu, Istri Kartun🪂**")
    sleep(1)
    await typew.edit("**IUHH DEMEN KOK SAMA 2D😖**")


@man_cmd(pattern="wibu(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WI WIII WIIII WIIII.....**")
    sleep(1)
    await typew.edit("__ARGHHH LARI ADA WIBUU!....__")
    sleep(1)
    await typew.edit("`🏃                        🧑‍🦽`")
    await typew.edit("`🏃                       🧑‍🦽`")
    await typew.edit("`🏃                      🧑‍🦽`")
    await typew.edit("`🏃                     🧑‍🦽`")
    await typew.edit("`🏃   `LARII ADA WIBU` 🧑‍🦽`")
    await typew.edit("`🏃                   🧑‍🦽`")
    await typew.edit("`🏃                  🧑‍🦽`")
    await typew.edit("`🏃                 🧑‍🦽`")
    await typew.edit("`🏃                🧑‍🦽`")
    await typew.edit("`🏃               🧑‍🦽`")
    await typew.edit("`🏃              🧑‍🦽`")
    await typew.edit("`🏃             🧑‍🦽`")
    await typew.edit("`🏃            🧑‍🦽`")
    await typew.edit("`🏃           🧑‍🦽`")
    await typew.edit("`🏃..Tolong..🧑‍🦽`")
    await typew.edit("`🏃           🧑‍🦽`")
    await typew.edit("`🏃            🧑‍🦽`")
    await typew.edit("`🏃             🧑‍🦽`")
    await typew.edit("`🏃              🧑‍🦽`")
    await typew.edit("`🏃               🧑‍🦽`")
    await typew.edit("`🏃                🧑‍🦽`")
    await typew.edit("`🏃                 🧑‍🦽`")
    await typew.edit("`🏃                  🧑‍🦽`")
    await typew.edit("`🏃                   🧑‍🦽`")
    await typew.edit("`🏃                    🧑‍🦽`")
    await typew.edit("`🏃                     🧑‍🦽`")
    await typew.edit("`🏃  Huh-Huh-Huh       🧑‍🦽`")
    await typew.edit("`🏃                   🧑‍🦽`")
    await typew.edit("`🏃                  🧑‍🦽`")
    await typew.edit("`🏃                 🧑‍🦽`")
    await typew.edit("`🏃                🧑‍🦽`")
    await typew.edit("`🏃               🧑‍🦽`")
    await typew.edit("`🏃              🧑‍🦽`")
    await typew.edit("`🏃             🧑‍🦽`")
    await typew.edit("`🏃            🧑‍🦽`")
    await typew.edit("`🏃           🧑‍🦽`")
    await typew.edit("`🏃          🧑‍🦽`")
    await typew.edit("`🏃         🧑‍🦽`")
    await typew.edit("__KOK MAKIN DEKET SI WIBU__")
    sleep(1)
    await typew.edit("`🏃       🧑‍🦽`")
    await typew.edit("`🏃      🧑‍🦽`")
    await typew.edit("`🏃     🧑‍🦽`")
    await typew.edit("`🏃    🧑‍🦽`")
    await typew.edit("**HARUS AKU LAWAN.!!!**")
    sleep(1)
    await typew.edit("🤼")
    sleep(2)
    await typew.edit("**DAN AKHIRNYA MEREKA JATUH CINTA DAN MENIKAH👨‍❤️‍👨**")


@man_cmd(pattern="sange(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("SAYANGGGGGGGGG 💕")
    sleep(1)
    await typew.edit("💝💘💓💗")
    sleep(1)
    await typew.edit("💞💕💗💘")
    sleep(1)
    await typew.edit("💝💘💓💗")
    sleep(1)
    await typew.edit("💞💕💗💘")
    sleep(1)
    await typew.edit("💘💞💗💕")
    sleep(1)
    await typew.edit("💘💞💕💗")
    sleep(1)
    await typew.edit("EMMMMMM🥺🥺🥺")
    sleep(1)
    await typew.edit("💝💘💓💗")
    await typew.edit("💞💕💗💘")
    await typew.edit("💘💞💕💗")
    await typew.edit("SAYANG")
    sleep(1)
    await typew.edit("AKU 👉👈")
    sleep(1)
    await typew.edit("SANGE 👉👈 😘😘")
    sleep(1)
    await typew.edit("💘💘💘💘")
    sleep(1)
    await typew.edit("SAYANG")
    sleep(1)
    await typew.edit("AYO NGEWE🤭🤭")
    sleep(1)
    await typew.edit("PLISS🥺🥺")
    sleep(1)
    await typew.edit("AKU SANGE😋😋")
    sleep(1)
    await typew.edit("I LOVE YOUUUU")
    sleep(1)
    await typew.edit("AH AH AH BEIBB")
    sleep(1)
    await typew.edit("💦💦💦💦")
    sleep(1)
    await typew.edit("OH BABY")
    sleep(1)
    await typew.edit("AKU SANGE SAYANG💞")


@man_cmd(pattern="asss(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Salam dulu biar sopan....`")
    sleep(2)
    await typew.edit("`A`")
    await typew.edit("`As`")
    await typew.edit("`Ass`")
    await typew.edit("`Assa`")
    await typew.edit("`Assal`")
    await typew.edit("`Assala`")
    await typew.edit("`Assalam`")
    await typew.edit("`Assalamu`")
    await typew.edit("`Assalamu'a`")
    await typew.edit("`Assalamu'al`")
    await typew.edit("`Assalamu'ala`")
    await typew.edit("`Assalamu'alai`")
    await typew.edit("`Assalamu'alaik`")
    await typew.edit("`Assalamu'alaiku`")
    await typew.edit("`Assalamu'alaikum`")
    sleep(3)
    await typew.edit("**YANG GA JAWAB, FIX ATHEISS!!**")


@man_cmd(pattern="shr(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`WOYYY PARA MANUSIA GA GUNA....`")
    sleep(2)
    await typew.edit("`Sa`")
    await typew.edit("`Saa`")
    await typew.edit("`Saaa`")
    await typew.edit("`Saaahh`")
    await typew.edit("`Saaahhhuu`")
    await typew.edit("`Saaahhhuuu`")
    await typew.edit("`Saaahhhuuuu`")
    await typew.edit("`Saaahhhuuuuu`")
    await typew.edit("`Saaahhhuuuuuur`")
    await typew.edit("`Saaahhhuuuuuurr`")
    await typew.edit("`Saaahhhuuuuuurrr`")
    await typew.edit("`Saaahhhuuuuuurrrr`")
    await typew.edit("`Saaahhhuuuuuurrrrr`")
    await typew.edit("`Saaahhhuuuuuurrrrrr`")
    await typew.edit("`Saaahhhuuuuuurrrrrrr`")
    await typew.edit("`Saaahhhuuuuuurrrrrrrr`")
    await typew.edit("`Saaahhhuuuuuurrrrrrrrr`")
    await typew.edit("`Saaahahuuuuuurrrrrrrrrr`")
    sleep(3)
    await typew.edit("**SAHUR COK, UDAH BANYAK DOSA GA PUASA LU!!**")


CMD_HELP.update(
    { 
        "animasi1": f"`{cmd}wibu` ; `{cmd}wibu2`\
    \nUsage: ntahlah gabut doang.\
    \n\n`{cmd}sange`\
    \nUsage: bocah sagapung\
    \n\n`{cmd}asss`\
    \nUsage: assalamu'alaikum.\
    \n\n`{cmd}shr`\
    \nUsage: Sahur kak"
    }
)
